trigger:
- main

pool: #linux-container-instances
  vmImage: ubuntu-latest
jobs:
- job: checkout

  steps:
  - checkout: self


- job: azurecli
  dependsOn: checkout
  condition: succeeded('checkout')
  steps:
  

    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'subscription1(cb746d33-61f2-4005-a6e1-323245542be4)'
        KeyVaultName: 'keyVault-fz378z'
        SecretsFilter: '*'
        RunAsPreJob: true
        



#Themes
#    - task: AzureCLI@2
#      inputs:
#        azureSubscription: 'subscription1(cb746d33-61f2-4005-a6e1-323245542be4)'
#        scriptType: 'bash'
#        scriptLocation: 'inlineScript'
#        inlineScript: 'az storage file upload-batch --destination https://$(storageAccountName).file.core.windows.net/wordpress --destination-path /wordpress/wp-content/themes --source $(System.DefaultWorkingDirectory)/themes --account-name $(storageAccountName) --account-key $(storageAccessKey)'

#Plugins
#    - task: AzureCLI@2
#      inputs:
#        azureSubscription: 'subscription1(cb746d33-61f2-4005-a6e1-323245542be4)'
#        scriptType: 'bash'
#        scriptLocation: 'inlineScript'
#        inlineScript: 'az storage file upload-batch --destination https://$(storageAccountName).file.core.windows.net/wordpress --destination-path /wordpress/wp-content/plugins --source $(System.DefaultWorkingDirectory)/themes --account-name $(storageAccountName) --account-key $(storageAccessKey)'

#Replace word in file
#gets variable from keyvault and inserts it into file. Need to add keyword as a filler into the document, so that the command has a word to reference.

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'subscription1(cb746d33-61f2-4005-a6e1-323245542be4)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'cp $(System.DefaultWorkingDirectory)/wp-config-sample.php $(System.DefaultWorkingDirectory)/wp-config.php'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'subscription1(cb746d33-61f2-4005-a6e1-323245542be4)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'find $(System.DefaultWorkingDirectory) -name wp-config.php -exec sed -i s/$(dbname)/dbname/g'
        
#'find $(System.DefaultWorkingDirectory) -name wp-config.php -exec sed -i s/$(dbname)/dbname/g'

        #Config File
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'subscription1(cb746d33-61f2-4005-a6e1-323245542be4)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az storage file upload --source $(System.DefaultWorkingDirectory)/wp-config.php --account-name $(storageAccountName) --account-key $(storageAccessKey) --share-name wordpress'